name: Deploy to heroku.
on:
  push:
    branches: [Main]

# Workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out repository.
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: ML Docker Deployment in Heroku. 
        uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name 
        with:
          # Variables for web Heroku app.

          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          # Dockerfile in the root folder
          dockerfile_directory: ./

          # Dockerfile name.
          dockerfile_name: Dockerfile

          # Additional options of docker build command.
          docker_options: "--no-cache"

          # (Optional, default: "web")
          # Process type for which you want the docker container to be uploaded.
          process_type: web
